- hosts: all
  become: true
  
  tasks:
    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: "Check if git package is installed or not "
      command: rpm -q git
      register: git_package_check
      ignore_errors: true
      when: "'git' in ansible_facts.packages"

    - name: Install package if not present 
      ansible.builtin.package:
        name: git
        state: present
      when: git_package_check is failed 