---
- hosts: all
  become: true
  vars:
   name: sweety
  tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: latest

    - name: copy index.html
      copy: 
        src: index.html
        dest: /var/www/html/index.html

    - name: Enable httpd
      service: 
        name: httpd
        state: started
        enabled: true
...